version: "3.8"

services:
  api:
    build: apps/api
    networks:
      - backend
    environment:
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}
      - REDIS_RATE_LIMIT_URL=${REDIS_URL:-redis://redis:6379}
      - PORT=${PORT:-3002}
      - HOST=${HOST:-0.0.0.0}
      - USE_DB_AUTHENTICATION=${USE_DB_AUTHENTICATION}
      #- PLAYWRIGHT_MICROSERVICE_URL=${PLAYWRIGHT_MICROSERVICE_URL:-http://playwright-service:3000}
      - NUM_WORKERS_PER_QUEUE=${NUM_WORKERS_PER_QUEUE}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL}
      - MODEL_NAME=${MODEL_NAME:-gpt-4o}
      - SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}
      - LLAMAPARSE_API_KEY=${LLAMAPARSE_API_KEY}
      - LOGTAIL_KEY=${LOGTAIL_KEY}
      - BULL_AUTH_KEY=${BULL_AUTH_KEY}
      - TEST_API_KEY=${TEST_API_KEY}
      - POSTHOG_API_KEY=${POSTHOG_API_KEY}
      - POSTHOG_HOST=${POSTHOG_HOST}
      - SUPABASE_ANON_TOKEN=${SUPABASE_ANON_TOKEN}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_TOKEN=${SUPABASE_SERVICE_TOKEN}
      - SCRAPING_BEE_API_KEY=${SCRAPING_BEE_API_KEY}
      - SELF_HOSTED_WEBHOOK_URL=${SELF_HOSTED_WEBHOOK_URL}
      - LOGGING_LEVEL=${LOGGING_LEVEL}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - redis
      - db
    ports:
      - "3002:3002"
    command: ["pnpm", "run", "start"]

  redis:
    image: redis:7.4-alpine
    networks:
      - backend
    command: redis-server --bind 0.0.0.0
    volumes:
      - redis-data:/data

  db:
    image: supabase/postgres:15.6.1.115
    ports:
      - "5432:5432"
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    environment:
      POSTGRES_PASSWORD: postgres
    networks:
      - backend
    volumes:
      - supabase-data:/var/lib/postgresql/data

  studio:
    image: supabase/studio:latest
    ports:
      - "8000:8000"
    environment:
      SUPABASE_URL: http://db:5432
      SUPABASE_ANON_TOKEN: "your-anon-key-here" # Replace with actual anon key
      SUPABASE_SERVICE_ROLE_KEY: "your-service-role-key-here" # Replace with actual service role key
      POSTGRES_PASSWORD: postgres
    depends_on:
      - db
    networks:
      - backend

volumes:
  redis-data:
  supabase-data:

networks:
  backend:
    driver: bridge
