version: "3.8"

services:
  api:
    build: /api
    networks:
      - backend
    environment:
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}
      - REDIS_RATE_LIMIT_URL=${REDIS_URL:-redis://redis:6379}
      - PORT=${PORT:-3002}
      - HOST=${HOST:-0.0.0.0}
      - USE_DB_AUTHENTICATION=${USE_DB_AUTHENTICATION}
      #- PLAYWRIGHT_MICROSERVICE_URL=${PLAYWRIGHT_MICROSERVICE_URL:-http://playwright-service:3000}
      - NUM_WORKERS_PER_QUEUE=${NUM_WORKERS_PER_QUEUE}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL}
      - MODEL_NAME=${MODEL_NAME:-gpt-4o}
      - SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}
      - LLAMAPARSE_API_KEY=${LLAMAPARSE_API_KEY}
      - LOGTAIL_KEY=${LOGTAIL_KEY}
      - BULL_AUTH_KEY=${BULL_AUTH_KEY}
      - TEST_API_KEY=${TEST_API_KEY}
      - POSTHOG_API_KEY=${POSTHOG_API_KEY}
      - POSTHOG_HOST=${POSTHOG_HOST}
      - SUPABASE_ANON_TOKEN=${SUPABASE_ANON_TOKEN}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_TOKEN=${SUPABASE_SERVICE_TOKEN}
      - SCRAPING_BEE_API_KEY=${SCRAPING_BEE_API_KEY}
      - SELF_HOSTED_WEBHOOK_URL=${SELF_HOSTED_WEBHOOK_URL}
      - LOGGING_LEVEL=${LOGGING_LEVEL}
      - MAX_CPU=${MAX_CPU}
      - MAX_RAM=${MAX_RAM}
      - ADMIN_AUTH_TOKEN=${ADMIN_AUTH_TOKEN}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - redis
    ports:
      - "3002:3002"
    command: ["pnpm", "run", "start"]

  redis:
    image: redis:7.4-alpine
    networks:
      - backend
    command: redis-server --bind 0.0.0.0
    volumes:
      - redis-data:/data

volumes:
  redis-data:

networks:
  backend:
    driver: bridge
