version: "3.8"

services:
  api:
    build: apps/api
    networks:
      - backend
    environment:
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}
      - REDIS_RATE_LIMIT_URL=${REDIS_URL:-redis://redis:6379}
      - PORT=${PORT:-3002}
      - HOST=${HOST:-0.0.0.0}
      - USE_DB_AUTHENTICATION=${USE_DB_AUTHENTICATION}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - redis
    ports:
      - "3002:3002"
    command: ["pnpm", "run", "start"]

  redis:
    image: redis:6.2-alpine
    networks:
      - backend
    command: redis-server --bind 0.0.0.0
    volumes:
      - redis-data:/data

volumes:
  redis-data:

networks:
  backend:
    driver: bridge
